### ISSUE TITLE
Facing below crash in iOS when integrating using pod (Xcode 15.0)

### ISSUE THREAD

**Issue by velmurugansubramaniam2** [fattmerchantorg/Fattmerchant-iOS-SDK#87]
dyld[5995]: Symbol not found: _OBJC_CLASS_$_NSString
  Referenced from: <59D1CD20-5637-3E48-BA10-A52B603D0489> /private/var/containers/Bundle/Application/097C65C6-423B-49F6-9098-95999C2B0B7A/Runner.app/Runner
  Expected in:     <A69917C4-CBE1-3D80-BAFB-6544C214675A> /private/var/containers/Bundle/Application/097C65C6-423B-49F6-9098-95999C2B0B7A/Runner.app/Frameworks/Fattmerchant.framework/Fattmerchant

**Comment by thomasvidas** [comment]
This error may happen because you have not included the `Foundation` framework in your iOS project. Be sure to include it as one of the first frameworks in your project. If that doesn't work, [try updating to XCode 15.1 or higher](https://developer.apple.com/forums/thread/735610)
