### ISSUE TITLE
Payment using credit card using inbuilt API call without Mobile Reader.

### ISSUE THREAD

**Issue by sojitrajayumedex** [fattmerchantorg/Fattmerchant-iOS-SDK#9]
Currently, application is accepting payment using a mobile reader using the following method.

```
    omni?.takeMobileReaderTransaction(request: createTransactionRequest(), completion: { _ in
      self.log("Finished transaction successfully")
    }, error: { error in
      self.log(error)
    })
```
We have a specific requirement to accept payment without using any device.

The client will enter his credit card information and payment should be done using the tokenized method through the application only.

**Comment by tuliot** [comment]
@sojitrajayumedex , the feature of taking a payment without using the mobile reader is under development and will be available in very soon in version 1.4.0. I will post here and let you know when it is available

**Comment by sojitrajayumedex** [comment]
By when I can expect it? As we have to also release our app. If you can let me know the expected date then it will be helpful for us.

**Comment by tuliot** [comment]
@sojitrajayumedex 1.4.0 Is scheduled to be available this Saturday evening
